author: eccentric_nz
description: Chunk generator for the TARDIS plugin
main: me.eccentric_nz.tardischunkgenerator.TARDISWorld
name: TARDISChunkGenerator
load: startup
url: http://dev.bukkit.org/server-mods/tardis/
version: '1.0c'
